name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out git repository
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: ./react-app
        run: |
          yarn install --frozen-lockfile

      - name: Build
        working-directory: ./react-app
        run: |
          yarn build

      - name: Test
        working-directory: ./react-app
        run: |
          yarn test --verbose

      - name: Run examples
        working-directory: ./react-app
        run: |
          yarn example-1
          yarn example-2
          yarn example-3
          yarn example-4
          yarn example-5
          yarn example-6
          yarn example-7
          yarn example-8
          yarn example-9
