name: Retry Publish Packages to NPM Registry

on:
  workflow_dispatch:
    inputs:
      warning:
        type: boolean
        description: "WARNING - Doing a release while other Github actions are running can cause errors. Make sure no other actions are running before continuing. https://github.com/lerna/lerna/issues/3115"
        required: true
        default: true
      distTag:
        description: Distribution Tag (e.g. latest, beta, alpha, etc)
        default: "latest"
        required: true
env:
  DIST_TAG: ${{ github.event.inputs.distTag }}

jobs:
  authorize:
    name: Authorize
    runs-on: ubuntu-latest
    steps:
      - name: ${{ github.actor }} permission check to do a release
        uses: "lannonbr/repo-permission-check-action@2.0.2"
        with:
          permission: "write"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: [authorize]
    strategy:
      matrix:
        node-version: [ 16.x ]
    env:
      LERNA_PACKAGE_VERSION: ''
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Configure NPM User
        if: ${{ env.DRY_RUN == 'false' }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH_TOKEN }}" > ~/.npmrc
          npm whoami

      - name: Retry Release (NPM)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn lerna publish from-package --dist-tag ${{ env.DIST_TAG }} --yes
